### ISSUE TITLE
Add Pling Store link on README

### ISSUE THREAD

**Issue by VihagChaturvedi** [Kyliekyler/MAGNETAR#10]
It wasn't easy to find the place to download from and the releases page is misguiding

Please add the pling store link on the README or update the releases page on GH

**Comment by VihagChaturvedi** [comment]
In addition to this, I can't seem to switch modes. When I run `magnetar` on Termux, it says command not found, am I missing smth? Magnetar shows up in Notifications tho

**Comment by ManOfDiamond** [comment]
> In addition to this, I can't seem to switch modes. When I run `magnetar` on Termux, it says command not found, am I missing smth? Magnetar shows up in Notifications tho

Glancing at the wiki once would be a good idea

**Comment by Kyliekyler** [comment]
> It wasn't easy to find the place to download from and the releases page is misguiding
> 
> Please add the pling store link on the README or update the releases page on GH

Yeah I would add the pling on the README, I will not close this issue until added. Release page is used for MAGNETAR+ users so it will stay as it is. And that being said for future users that might ended up finding the download link on GitHub here's the link below:

https://www.pling.com/p/1465345

**Comment by VihagChaturvedi** [comment]
> > In addition to this, I can't seem to switch modes. When I run `magnetar` on Termux, it says command not found, am I missing smth? Magnetar shows up in Notifications tho
> 
> Glancing at the wiki once would be a good idea

Nothing useful was found, the wiki is all commands, here is a ss highlighting my issue
![IMG_20220803_104420](https://user-images.githubusercontent.com/45941793/182530108-49f8ce89-0e65-4b58-a6c3-56db2d255cb6.jpg)


U can see the magnetar icon in the notifs, but termux doesn't seem to find it

Here is my Magisk (grey update icon indicates no updates are available)

![IMG_20220803_105312](https://user-images.githubusercontent.com/45941793/182530419-8fcaa11a-8062-4051-b3ed-4f81ccaa6e75.jpg)

Here is the log file while u are at it

[Pastebin](https://pastebin.com/c7TW43yx)

**Comment by Kyliekyler** [comment]
> > > In addition to this, I can't seem to switch modes. When I run `magnetar` on Termux, it says command not found, am I missing smth? Magnetar shows up in Notifications tho
> > 
> > 
> > Glancing at the wiki once would be a good idea
> 
> Nothing useful was found, the wiki is all commands, here is a ss highlighting my issue ![IMG_20220803_104420](https://user-images.githubusercontent.com/45941793/182530108-49f8ce89-0e65-4b58-a6c3-56db2d255cb6.jpg)
> 
> U can see the magnetar icon in the notifs, but termux doesn't seem to find it
> 
> Here is my Magisk (grey update icon indicates no updates are available)
> 
> ![IMG_20220803_105312](https://user-images.githubusercontent.com/45941793/182530419-8fcaa11a-8062-4051-b3ed-4f81ccaa6e75.jpg)
> 
> Here is the log file while u are at it
> 
> [Pastebin](https://pastebin.com/c7TW43yx)

You're supposed to run it on root like
```
$ su -c magnetar
```

or

```
$ su
# magnetar
```

**Comment by VihagChaturvedi** [comment]
Got it, thx!

**Comment by Kyliekyler** [comment]
> Got it, thx!
> 
> I think it is a good idea to mention the super user req. At the very start of the documentation to ensure there is no confusion
> 
> In Linux there is a convention followed for implying such commands(as you have alr mentioned)
> 
> Maybe this may help clear up things for other users who are not aware of this
> 
> `$ magnetar --ai train` <---- User `# magnetar --ai train` <---- Root

Check out the wiki now, I did put your suggestion into consideration. Thanks!

https://github.com/Kyliekyler/MAGNETAR/wiki/documentation

Also I've added already the pling download link on the release page, and I think it's better that way since it would be the first user to get looking at rushing to download.

If you already feel satisfied with my answers you can close this issue and if not you can still give suggestions.

**Comment by VihagChaturvedi** [comment]
Would be better IMO to put the pling store link in installation, but considering u do want to promote MAGNATAR+ its fine

maybe i will volunteer to improve the readme a bit with a PR, cuz i really do like this project and can see some things improved(^^)
