### ISSUE TITLE
Notification not showing again.

### ISSUE THREAD

**Issue by hamzamaqsood877** [Kyliekyler/MAGNETAR#12]
I disabled notification service but I'm trying to turn in on back, it says that service has started but no notification in showing up.. What should I do?

**Comment by Kyliekyler** [comment]
Run these following commands in sequence:
```
magnetar --notification disable
magnetar --notification enable
```

then file a bugreport using the following command: `magnetar --bugreport`

**Comment by hamzamaqsood877** [comment]
Done
