### ISSUE TITLE
Make per-app mode profiles available again to regular users

### ISSUE THREAD

**Issue by DodoLeDev** [Kyliekyler/MAGNETAR#13]
### Hi!
I've been using your module for a while now, and I absolutely love the way it completely changed the behavior of my low-end device!

I can even boast of having a device faster and smoother than mid-end ones! 😂

**However, an update changed too much things for my case: the ability to set per-app mode profiles.**

It was the feature I used most, and now it's gone for me 😢

Having to pay for the new features is perfectly understandable! But having to pay for features that have been offered for free for quite some time....That's not very nice! 😒

So, **is there any way to make per-app mode profiles available again to regular users?** 🙏🏼

_I hope that you'll understand...._

Best regards

> _- A user that really believe in this project_ 💪🏼

**Comment by Kyliekyler** [comment]
We understand that removing such a feature is a difficult decision to make, but we made this adjustment to encourage users to interact more with the future MAGNETAR app, and users also prefer to utilize manually selected modes over setting per-app profiles.

I'll close the issue and label it as completed, but please feel free to reopen or remark at any time; we welcome your feedback :)
