### ISSUE TITLE
MAGNETAR INSTALLATION

### ISSUE THREAD

**Issue by deanseiyaa** [Kyliekyler/MAGNETAR#15]
Does the app even need the KernelSU even though I have the magisk? I can't seem to add her as the Module.

**Comment by Kyliekyler** [comment]
Could you provide the magisk installation log?

**Comment by deanseiyaa** [comment]
> Could you provide the magisk installation log?

@Kyliekyler thank you for the reply! I had just finished installing her and she worked after I went and DL'd her from the website. 

I have a question but you don't have to answer it good sir... "What inspired you to make this? I understand if it is about pure hobby or is because you want to earn $?"

**Comment by Kyliekyler** [comment]
> > Could you provide the magisk installation log?
> 
> @Kyliekyler thank you for the reply! I had just finished installing her and she worked after I went and DL'd her from the website.
> 
> I have a question but you don't have to answer it good sir... "What inspired you to make this? I understand if it is about pure hobby or is because you want to earn $?"

Alright Ill be closing the case since you're able to install it already. Well the answer to your question would be pure hobby as it started years before it starts to earn money as users demand to have a premium version of the project.
