### ISSUE TITLE
MAGNETAR EACCES (Permission Denied)

### ISSUE THREAD

**Issue by deanseiyaa** [Kyliekyler/MAGNETAR#16]
While attempting to open chrome, doesn't open.
Opening Toast Notification from MAGNETAR > TERMUX > "cannot open file :/data/adb/modules/04244E57/system/etc/C5577079/C55770791.log: open failed: EACCES (Permission denied)"

**Comment by Kyliekyler** [comment]
File a bugreport using `magnetar --bugreport`

**Comment by deanseiyaa** [comment]
Thank you! I sent the bug report just now. However I just posted "Cannot open chrome while MAGNETAR is on". Telegram: Dean Seiyaa

**Comment by Kyliekyler** [comment]
> Thank you! I sent the bug report just now. However I just posted "Cannot open chrome while MAGNETAR is on". Telegram: Dean Seiyaa

Thats fine, Ill take a look on it. Thanks.
