### ISSUE TITLE
Magnetar+ required problem 

### ISSUE THREAD

**Issue by Kiraxx69** [Kyliekyler/MAGNETAR#18]
[
[magisk_install_log_2024-02-26T03.17.42.log](https://github.com/Kyliekyler/MAGNETAR/files/14397889/magisk_install_log_2024-02-26T03.17.42.log)
I give u the list log

**Comment by Kyliekyler** [comment]
Github releases is for magnetar+ users, if you haven't registered to magnetar+ then it will deny the installation as the key of the device is not registered.

We still have the free version at https://www.pling.com/p/1465345

I'll be closing the issue now, thanks.
