### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by mikropsoft** [Kyliekyler/MAGNETAR#20]
Can this module be used with [yakt](https://github.com/NotZeetaa/YAKT)?

**Comment by mikropsoft** [comment]
And what I don't understand is, is there any app installed for this module or does it come with a notification message because for me it didn't appear if these existed.

**Comment by Kyliekyler** [comment]
> Can this module be used with [yakt](https://github.com/NotZeetaa/YAKT)?

Your choice. We prefer not to use it alongside magnetar, anyway all things that are changed by any other module/kernel manager that also changed by magnetar will all get overridden.

> And what I don't understand is, is there any app installed for this module or does it come with a notification message because for me it didn't appear if these existed.

Theres an app but only for notification purposes and will not appear on the app drawer.
