### ISSUE TITLE
Is there any way to exclude an app from sleep mode? E.g I am uploading data on google photos and it stops that in background

### ISSUE THREAD

**Issue by usama03080302** [Kyliekyler/MAGNETAR#21]
Is there any way to exclude an app from sleep mode? E.g I am uploading data on google photos and it stops that in background

**Comment by Kyliekyler** [comment]
Could you run `magnetar --bugreport` so that I could check your configurations?

**Comment by usama03080302** [comment]
> Could you run `magnetar --bugreport` so that I could check your configurations?

done

**Comment by usama03080302** [comment]
> Could you run `magnetar --bugreport` so that I could check your configurations?
Is there any solution? I didn't even backed up my previous kernel settings

**Comment by Kyliekyler** [comment]
> Is there any solution? I didn't even backed up my previous kernel settings

Yes theres a solution to it, try setting different ram profile on magnetar balance or light. Ill be taking a look on sleep mode too, but I could see that you could try to disable the ram management and perform a reboot.

Set light or balance ram profile
`magnetar --ram <profile>`

Disable ram profile
`magnetar --ram disable`

**Comment by usama03080302** [comment]
Thanks bro it resolved my issue, hope so it won't affect that much on my device's performance, the best thing about magnetar was that it improved my phone's battery life so much. But now I disabled ram management, let's see how that affects my battery. But yeah it resolved my issue and that's great.
