### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by daedaevibin** [Kyliekyler/MAGNETAR#22]
Simply says "Magnetar+ Required" and doesn't install with no other information.

**Comment by Kyliekyler** [comment]
> Simply says "Magnetar+ Required" and doesn't install with no other information.

Usually this happens when you're installing builds coming from github and if you're not a magnetar+ user, make sure to read the release notes before installing it. If the issue persist, please do provide the installation logs so we could check.

**Comment by Kyliekyler** [comment]
Please do install builds from pling if you still experiencing the issue. Issue will be closed, thanks.

**Comment by daedaevibin** [comment]
would not be sure how to become a magnetar+ user as it has absolutely zero instruction in the log as well as I only received boot loop issues from magisk and have stopped using it. Thanks anyway!

**Comment by Kyliekyler** [comment]
> would not be sure how to become a magnetar+ user as it has absolutely zero instruction in the log as well as I only received boot loop issues from magisk and have stopped using it. Thanks anyway!

First the wiki is available and the documentation on how to be a magnetar+ user is here https://github.com/Kyliekyler/MAGNETAR/wiki/Registration. Secondly magnetar could not cause a bootloop as it is not getting installed on your device as you were installing builds from github. Lastly it's also included on the release page that the public builds can be downloaded via pling.

**Comment by daedaevibin** [comment]
> > would not be sure how to become a magnetar+ user as it has absolutely zero instruction in the log as well as I only received boot loop issues from magisk and have stopped using it. Thanks anyway!
> 
> First the wiki is available and the documentation on how to be a magnetar+ user is here https://github.com/Kyliekyler/MAGNETAR/wiki/Registration. Secondly magnetar could not cause a bootloop as it is not getting installed on your device as you were installing builds from github. Lastly it's also included on the release page that the public builds can be downloaded via pling.

the issue was I actually tried both here on github and pling, but thanks for your help

**Comment by Kyliekyler** [comment]
Well but theres no logs provided to identify what's causing the issue but to be honest most of the issues regarding those are fixed when they installed the pling build as I intentionally made it that way.
