### ISSUE TITLE
MAGNETAR + REQUIRED

### ISSUE THREAD

**Issue by KillerModder** [Kyliekyler/MAGNETAR#24]
I'm installing magnetar through magisk and simply at the end of the installation it says MAGNETAR + REQUIRED (SORRY I DON'T KNOW IF IT'S A BASIC ERROR) it shows success when installing but when I go to see in magisk modules it doesn't appear (I'M TRANSLATING I'M BRAZILIAN) I'm going to put an image showing exactly what is appearing and also when I use (SU -C MAGNETAR) in termux it can't be found, please help me 
![Screenshot_20240809_175919](https://github.com/user-attachments/assets/74decfbb-8ef5-43c8-ada4-312dad829b69)

**Comment by KillerModder** [comment]
even after installing the version (whiskey) that is on the other platform it gives the same error when running in termux
![Screenshot_20240809_210304_Termux](https://github.com/user-attachments/assets/da895409-cb14-481a-a74a-757acc1dde1e)

**Comment by Kyliekyler** [comment]
Perhaps you might wanna check this

https://github.com/Kyliekyler/MAGNETAR/issues/23#issuecomment-2278761611

**Comment by Kyliekyler** [comment]
Can you install build from pling and provide the installation logs?

**Comment by KillerModder** [comment]
> Você pode instalar o build do pling e fornecer os logs de instalação?

Thank you very much friend, but I managed to solve it, it was just a few changes to your code
