### ISSUE TITLE
MAGNETAR+ REQUIRED

### ISSUE THREAD

**Issue by aungkondremerzlab** [Kyliekyler/MAGNETAR#26]
After Going back to modules it doesn't show that module is installed,or anything. 

Logs:
`- SETTING UP ENVIRONMENT...
  DONE
 
- ESTABLISHING CONNECTION...
  DONE
 
- FETCHING METADATA...
  DONE
 
- CHECKING FOR UPDATES...
  CURRENTLY UP-TO-DATE
 
- FETCHING ADDITIONAL RESOURCES...
  DONE
 
- CHECKING USER PRIVILEGES...
  MAGNETAR+ REQUIRED`

**Comment by ixaobao** [comment]
Yes, I had the same problem.

**Comment by rifsxd** [comment]
If you installed it from the module you got from GitHub then you need premium subscription which Magnetar+, so go get it from the pling link

**Comment by Kyliekyler** [comment]
Please see Issue #18, closing the case now.
