### ISSUE TITLE
 Magnetar Os error 38

### ISSUE THREAD

**Issue by Jagpreet888** [Kyliekyler/MAGNETAR#28]
Hello sir I'm use Kernel su version 11341 manager version v 1.0.1-48 show this problem> Preparing image
- Module size: 3.72 MB
e2fsck 1.45.4 (23-Sep-2019)
- Mounting image
- Error: Function not implemented (os error 38)
Error: Function not implemented (os error 38)

**Comment by Kyliekyler** [comment]
This is not magnetar error.
