### ISSUE TITLE
No Call Receive

### ISSUE THREAD

**Issue by adityadtr** [Kyliekyler/MAGNETAR#3]
[magne.log](https://github.com/Kyliekyler/MAGNETAR/files/4669502/magne.log)
[mode.txt](https://github.com/Kyliekyler/MAGNETAR/files/4669503/mode.txt)
Couldn't Recieve Calls.
Device: Realme 1 (4+64GB) (Mediatek Helio P60)
GSI: Bliss OS (BlessROM)

**Comment by Kyliekyler** [comment]
You we're referring to golf and this version is hotel. No more support for golf. And it was already fixed on hotel version onwards. Case closed.
