### ISSUE TITLE
Magnetar Golf not working

### ISSUE THREAD

**Issue by Akarshan1234** [Kyliekyler/MAGNETAR#5]
I was on Magnetar Beta release 3 then deleted that and installed magnetar golf now logs of Magnetar golf not coming
Logs of Br3 stuck in phone and those logs stopped after uninstalling Br3 module.Now i deleted that MAGNETAR folder but still folder of Magnetar Golf not coming

**Comment by Kyliekyler** [comment]
Golf has issues creating log directory try to create MAGNETAR folder on internal first then reboot. Also this is fixed on newer version so dont complain bout this issue as u were on older version. Case closed.
