### ISSUE TITLE
Schedtune.boost failed issue

### ISSUE THREAD

**Issue by WUIX69** [Kyliekyler/MAGNETAR#6]
**Good Morning sir Kyle**

I have an issue regarding schedtune.boost in my POCO M3 Device

Debug Log:
FAILED TO SET: dev/stune/background/schedtune.boost

**Is it fine ?.. Btw i'am using the latest one Magnetar (Mike)..

**Comment by Kyliekyler** [comment]
Ah yes this is fine, if it reports error it's reverting back to its original value so nothing to worry about. Case closed, thanks for giving feedback.

**Comment by WUIX69** [comment]
Thanks again brother love you <3
