### ISSUE TITLE
cant install in my custom rom

### ISSUE THREAD

**Issue by amritwagle** [Kyliekyler/MAGNETAR#7]
it dont install in my pixel plus merlin custom rom.
![Screenshot_20220104-192715](https://user-images.githubusercontent.com/30712391/148067843-e7554e3e-f538-4c1b-8bf8-3eab3e24c180.png)

**Comment by MrCarb0n** [comment]
go for latest version. 👍🏻

**Comment by MrCarb0n** [comment]
> it dont install in my pixel plus merlin custom rom. ![Screenshot_20220104-192715](https://user-images.githubusercontent.com/30712391/148067843-e7554e3e-f538-4c1b-8bf8-3eab3e24c180.png)

go for latest version. 👍🏻

**Comment by Kyliekyler** [comment]
This version is outdated nearly a year ago, you can download via the link that I provide and not those links that I do not provide. 

Get from here: https://www.pling.com/p/1465345/
