### ISSUE TITLE
Stuck on start mode

### ISSUE THREAD

**Issue by rhamadhany** [Kyliekyler/MAGNETAR#8]
Does magnetar not support on android 9? i was previously using android 10 it was running normally.. but on android 9 i was stuck in starting....mode, i've tried several different versions but it's the same

![Screenshot_20220122-230432](https://user-images.githubusercontent.com/77799700/150644074-1a443066-f6b5-4403-8d37-75eb346dcdd4.png)
![Screenshot_20220122-230825](https://user-images.githubusercontent.com/77799700/150644096-66343db6-3517-435e-b1fa-f29108dd7e46.png)

**Comment by Kyliekyler** [comment]
I need more info, contact me (Kyliekyler) on telegram.dog/MAGNETARCHAT

**Comment by betastar** [comment]
MAGNETAR DEBUG LOG
=============================================================
  VERSION | OSCAR (220731055)
=============================================================
  START OF [MAIN] @ THU MAR 17 08:48:35 2022 CST
  [03-17 08:48] FAILED TO SET: /proc/sys/kernel/sched_ravg_window_nr_ticks
  START OF [MAIN] @ THU MAR 17 08:50:43 2022 CST
  [03-17 08:50] FAILED TO SET: /proc/sys/kernel/sched_ravg_window_nr_ticks
  START OF [MAIN] @ THU MAR 17 08:55:58 2022 CST
  [03-17 08:56] FAILED TO SET: /proc/sys/kernel/sched_ravg_window_nr_ticks

**Comment by MrCarb0n** [comment]
@rhamadhany upgrade to OSCAR first.

**Comment by rhamadhany** [comment]
> @rhamadhany upgrade to OSCAR first.

I've tried the version LIMA, NOVEMBER, OSCAR beta 1-4.. and OSCAR stable in the latest version.. But it's all the same happens stuck in starting mode.. Besides that, I have also tried all the firmware on android 9 which is available for my phone except the custom rom.. And this only happens on Android 9, when I'm on Android 10 it runs normally.. But on xiaomi phones it can even run on android 8.1, But on xperia phones it doesn't run on android 9.. that's weird

**Comment by MrCarb0n** [comment]
> > @rhamadhany upgrade to OSCAR first.
> 
> I've tried the version LIMA, NOVEMBER, OSCAR beta 1-4.. and OSCAR stable in the latest version.. But it's all the same happens stuck in starting mode.. Besides that, I have also tried all the firmware on android 9 which is available for my phone except the custom rom.. And this only happens on Android 9, when I'm on Android 10 it runs normally.. But on xiaomi phones it can even run on android 8.1, But on xperia phones it doesn't run on android 9.. that's weird

did you file a bug report?

> `magnetar --bugreport`

**Comment by rhamadhany** [comment]
Not. I haven't done that yet, but I did chat with kyliekyler on telegram. He not asked for that so I didn't do it
