### ISSUE TITLE
Magnetar app does not exist in app drawer 

### ISSUE THREAD

**Issue by NimaAtashgah** [Kyliekyler/MAGNETAR#9]
After install magnetar with magisk 24.3 the app does not exist in app drawer but an auto processing of magnetar module works in status bar. Not just the magnetar a few another module has the same problem after install with magisk 24.3
My device is redmi note 9 pro joyeuse

**Comment by Kyliekyler** [comment]
Hello there, tbh that's only for notifications. It was intentionally made like that. So for that, may you close the issue since this isn't an issue to start with.

**Comment by NimaAtashgah** [comment]
Thanks for answer. Then how can I install the app for manual switch btw modes? I'm new in magisk and modules

**Comment by NimaAtashgah** [comment]
> Hello there, tbh that's only for notifications. It was intentionally made like that. So for that, may you close the issue since this isn't an issue to start with.

Thanks for answer. Then how can I install the app for manual switch btw modes? I'm new in magisk and modules
